"""initial

Revision ID: c27db0728ae7
Revises: None
Create Date: 2026-07-10 23:53:44.923635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27db0728ae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('max_position_ratio', sa.Float(), nullable=False),
    sa.Column('confirm_price', sa.Float(), nullable=False),
    sa.Column('trim_price', sa.Float(), nullable=False),
    sa.Column('failure_price', sa.Float(), nullable=False),
    sa.Column('outperform_condition', sa.Text(), nullable=False),
    sa.Column('underperform_action', sa.Text(), nullable=False),
    sa.Column('allow_buyback', sa.Boolean(), nullable=False),
    sa.Column('buyback_limit_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_cards_code'), 'exit_cards', ['code'], unique=False)
    op.create_index(op.f('ix_exit_cards_id'), 'exit_cards', ['id'], unique=False)
    op.create_index(op.f('ix_exit_cards_name'), 'exit_cards', ['name'], unique=False)
    op.create_table('holding_sync_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=False),
    sa.Column('position_type', sa.String(length=32), nullable=False),
    sa.Column('next_discipline', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_sync_baselines_code'), 'holding_sync_baselines', ['code'], unique=True)
    op.create_index(op.f('ix_holding_sync_baselines_id'), 'holding_sync_baselines', ['id'], unique=False)
    op.create_index(op.f('ix_holding_sync_baselines_name'), 'holding_sync_baselines', ['name'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=False),
    sa.Column('position_type', sa.String(length=32), nullable=False),
    sa.Column('next_discipline', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_code'), 'holdings', ['code'], unique=False)
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_name'), 'holdings', ['name'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('turnover_score', sa.Integer(), nullable=False),
    sa.Column('limit_up_count', sa.Integer(), nullable=False),
    sa.Column('leading_theme', sa.String(length=128), nullable=False),
    sa.Column('leader_state', sa.String(length=64), nullable=False),
    sa.Column('loss_effect', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_id'), 'market_snapshots', ['id'], unique=False)
    op.create_table('next_day_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.String(length=16), nullable=False),
    sa.Column('plan_type', sa.String(length=24), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('position_ratio', sa.Float(), nullable=False),
    sa.Column('holding_category', sa.String(length=32), nullable=False),
    sa.Column('risk_priority', sa.Integer(), nullable=False),
    sa.Column('classification_basis', sa.Text(), nullable=False),
    sa.Column('outperform_condition', sa.Text(), nullable=False),
    sa.Column('outperform_action', sa.Text(), nullable=False),
    sa.Column('expected_condition', sa.Text(), nullable=False),
    sa.Column('expected_action', sa.Text(), nullable=False),
    sa.Column('underperform_condition', sa.Text(), nullable=False),
    sa.Column('underperform_action', sa.Text(), nullable=False),
    sa.Column('confirm_price', sa.Float(), nullable=False),
    sa.Column('trim_price', sa.Float(), nullable=False),
    sa.Column('trim_condition', sa.Text(), nullable=False),
    sa.Column('trim_quantity', sa.Integer(), nullable=False),
    sa.Column('allow_buyback', sa.Boolean(), nullable=False),
    sa.Column('buyback_price', sa.Float(), nullable=False),
    sa.Column('buyback_condition', sa.Text(), nullable=False),
    sa.Column('max_buyback_quantity', sa.Integer(), nullable=False),
    sa.Column('reduce_price', sa.Float(), nullable=False),
    sa.Column('final_risk_price', sa.Float(), nullable=False),
    sa.Column('stop_loss_4pct', sa.Float(), nullable=False),
    sa.Column('limit_up_price', sa.Float(), nullable=False),
    sa.Column('auction_plan', sa.Text(), nullable=False),
    sa.Column('forbidden_actions', sa.Text(), nullable=False),
    sa.Column('risk_warnings', sa.Text(), nullable=False),
    sa.Column('review_expectation', sa.String(length=32), nullable=False),
    sa.Column('review_execution', sa.Text(), nullable=False),
    sa.Column('review_deviation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_day_plans_code'), 'next_day_plans', ['code'], unique=False)
    op.create_index(op.f('ix_next_day_plans_holding_id'), 'next_day_plans', ['holding_id'], unique=False)
    op.create_index(op.f('ix_next_day_plans_id'), 'next_day_plans', ['id'], unique=False)
    op.create_index(op.f('ix_next_day_plans_name'), 'next_day_plans', ['name'], unique=False)
    op.create_index(op.f('ix_next_day_plans_plan_date'), 'next_day_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_next_day_plans_plan_type'), 'next_day_plans', ['plan_type'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('traded_at', sa.DateTime(), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=False),
    sa.Column('position_ratio', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('stop_loss_price', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('compliant', sa.Boolean(), nullable=False),
    sa.Column('human_tags', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_logs_code'), 'trade_logs', ['code'], unique=False)
    op.create_index(op.f('ix_trade_logs_id'), 'trade_logs', ['id'], unique=False)
    op.create_index(op.f('ix_trade_logs_name'), 'trade_logs', ['name'], unique=False)
    op.create_table('trade_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('discipline_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('stock_context', sa.Text(), nullable=False),
    sa.Column('sector_context', sa.Text(), nullable=False),
    sa.Column('market_context', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('mistakes', sa.Text(), nullable=False),
    sa.Column('avoid_actions', sa.Text(), nullable=False),
    sa.Column('weakness_tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_reviews_code'), 'trade_reviews', ['code'], unique=False)
    op.create_index(op.f('ix_trade_reviews_id'), 'trade_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_trade_reviews_name'), 'trade_reviews', ['name'], unique=False)
    op.create_index(op.f('ix_trade_reviews_trade_id'), 'trade_reviews', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_reviews_trade_id'), table_name='trade_reviews')
    op.drop_index(op.f('ix_trade_reviews_name'), table_name='trade_reviews')
    op.drop_index(op.f('ix_trade_reviews_id'), table_name='trade_reviews')
    op.drop_index(op.f('ix_trade_reviews_code'), table_name='trade_reviews')
    op.drop_table('trade_reviews')
    op.drop_index(op.f('ix_trade_logs_name'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_id'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_code'), table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_next_day_plans_plan_type'), table_name='next_day_plans')
    op.drop_index(op.f('ix_next_day_plans_plan_date'), table_name='next_day_plans')
    op.drop_index(op.f('ix_next_day_plans_name'), table_name='next_day_plans')
    op.drop_index(op.f('ix_next_day_plans_id'), table_name='next_day_plans')
    op.drop_index(op.f('ix_next_day_plans_holding_id'), table_name='next_day_plans')
    op.drop_index(op.f('ix_next_day_plans_code'), table_name='next_day_plans')
    op.drop_table('next_day_plans')
    op.drop_index(op.f('ix_market_snapshots_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_holdings_name'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_code'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_holding_sync_baselines_name'), table_name='holding_sync_baselines')
    op.drop_index(op.f('ix_holding_sync_baselines_id'), table_name='holding_sync_baselines')
    op.drop_index(op.f('ix_holding_sync_baselines_code'), table_name='holding_sync_baselines')
    op.drop_table('holding_sync_baselines')
    op.drop_index(op.f('ix_exit_cards_name'), table_name='exit_cards')
    op.drop_index(op.f('ix_exit_cards_id'), table_name='exit_cards')
    op.drop_index(op.f('ix_exit_cards_code'), table_name='exit_cards')
    op.drop_table('exit_cards')
    op.drop_table('account_state')
    # ### end Alembic commands ###
