const LABELS: Record<string, string> = {
  STRONGER: '强于预期', MATCHED: '符合预期', WEAKER: '弱于预期',
  SLIGHTLY_WEAKER: '略弱于预期', INVALID: '预期证伪', UNKNOWN: '未知',
  EXIT_REQUIRED: '必须退出', REDUCE_REQUIRED: '必须减仓',
  EXPECTATION_INVALIDATED: '预期失效', STOP_LOSS_WARNING: '止损警告',
  NORMAL_HOLD: '正常持有', PROFIT_EXPANSION: '利润扩张',
  PROFIT_PROTECTION: '利润保护', DIVERGENCE_HOLD: '分歧持有',
  DEGRADED_DATA_OBSERVATION: '数据降级观察',
  manual: '手动数据', missing: '数据缺失', realtime: '实时数据', historical_close: '最新收盘参考',
  degraded: '数据降级', degraded_vwap: '均价线降级',
  planned: '已计划', completed: '已完成', done: '已完成',
  LOW: '低', MEDIUM: '中', HIGH: '高',
  FLOW_NEW_HIGH: '资金新高', FLOW_PEAK_REVERSAL: '资金见顶回落',
  FLOW_TURN_NEGATIVE: '资金由正转负',
  REDUCE: '减仓', PROTECT: '利润保护', EXIT: '退出', HOLD: '持有', OBSERVE: '观察',
  REDUCE_ALL: '全面减仓', BLOCK_NEW_POSITION: '禁止新开仓',
  NO_T: '禁止做T', INTRADAY_T: '日内做T', ROLLING_T: '滚动做T',
  PRICE: '价格', EXPECTATION: '预期', VOLUME_PRICE: '量价', ACTION: '动作',
  EXTREME_STRONG: '极强', STRONG: '强势', NEUTRAL: '中性', WEAK: '弱势',
  REPAIR: '修复阶段', EBB: '退潮阶段',
  STRONG_TO_STRONGER: '强势转更强', WEAK_TO_STRONG: '弱转强',
  DIVERGENCE_TO_CONSENSUS: '分歧转一致', CONSENSUS_TO_DIVERGENCE: '一致转分歧',
  STRONG_TO_WEAK: '强转弱', REPAIR_SUCCESS: '修复成功', REPAIR_FAILED: '修复失败',
  VWAP_BROKEN: '跌破分时均价线', VWAP_RECOVERED: '收复分时均价线',
  VOLUME_PRICE_WEAKENING: '量价转弱', VOLUME_PRICE_STRENGTHENING: '量价转强',
  PROFIT_DRAWDOWN_WARNING: '利润回撤预警', TIME_STOP_TRIGGERED: '时间止损触发',
  HIGH_OPEN_FAILED_BREAKOUT: '高开冲板失败', LIMIT_UP_OPENED: '涨停开板',
  BELOW_VWAP: '位于分时均价线下方', ABOVE_VWAP: '位于分时均价线上方',
  VOLUME_EXPANSION: '放量', VOLUME_CONTRACTION: '缩量',
  EXPECTATION_VOLUME_BREAKDOWN: '预期与量价同步转弱',
  EXPECTATION_DOWNGRADE: '预期下调', VWAP_BREAKDOWN: '跌破分时均价线',
  VWAP_STRONG: '分时均价线上方强势', VOLUME_PRICE_NEUTRAL: '量价中性',
  HIGH_VOLUME_STAGNATION: '高位放量滞涨', PROFIT_TO_LOSS_RISK: '浮盈转亏风险',
  DIVERGENCE_RESEAL: '分歧后回封', REPAIR_CONFIRMED: '修复确认',
  REVERSAL_CONFIRMED: '盘中反转确认', REVERSAL_PENDING: '盘中反转待确认',
  REVERSAL_CONFIRMED_HOLD: '反转确认后观察持有', REVERSAL_PENDING_HOLD: '反转观察持有',
  INVALIDATION_TO_REVERSAL: '预期证伪后转入反转确认',
  INTRADAY_REVERSAL_PENDING: '盘中反转待确认',
  INTRADAY_REVERSAL_CONFIRMED: '盘中反转确认',
  RISK_RECOVERY_CONFIRMED: '风险修复确认',
  HIGH_SELL_WINDOW: '冲高兑现窗口', PANIC_SELL_GUARD: '禁止恐慌卖出',
  CONTRARIAN_ADD_EVALUATION: '逆势补仓评估资格',
  SECTOR_REPAIR: '板块修复', TREND_BREAKOUT: '趋势突破',
  SLIGHTLY_STRONGER: '略强于预期',
  SECTOR_MIGRATION_CONFIRMED: '跨板块订单流迁移候选',
  SECTOR_FLOW_PEAK_REVERSAL: '板块订单流方向估算高位回落', HIGH_DRAWDOWN: '高点明显回撤',
  SECTOR_DISTRIBUTION_RISK: '板块高位派发风险',
  SECTOR_FLOW_TURN_OUT: '板块订单流方向估算由正转负',
  SECTOR_FLOW_TURN_IN: '板块订单流方向估算由负转正',
  SECTOR_FLOW_WEAKENING: '板块订单流方向估算边际转弱',
  SECTOR_FLOW_RECOVERY: '板块订单流方向估算边际修复',
  SHRINKING_RISE_DIVERGENCE: '缩量上涨与订单流背离',
  SHRINKING_REBOUND_UNCONFIRMED: '缩量反弹未确认',
  SHRINKING_DECLINE_EXHAUSTION_WATCH: '缩量下跌抛压衰减观察',
  SHRINKING_DECLINE_WEAKNESS: '缩量下跌但订单流仍弱',
  SHRINKING_PULLBACK_SUPPORT_WATCH: '缩量回踩支撑观察',
  PRICE_VOLUME_PATTERN_SHRINKING_RISE_SUPPORTED: '缩量上涨但抛压较轻',
  PRICE_VOLUME_PATTERN_SHRINKING_RISE_FRAGILE: '缩量上涨承接脆弱',
  PRICE_VOLUME_PATTERN_SHRINKING_RISE_PENDING: '缩量上涨待确认',
  PRICE_VOLUME_PATTERN_SHRINKING_PULLBACK_HOLD: '缩量回踩未破分时均价线',
  PRICE_VOLUME_PATTERN_VOLUME_RISE_CONFIRMED: '放量上涨获得确认',
  PRICE_VOLUME_PATTERN_VOLUME_RISE_STALLED: '放量上涨但承载效率下降',
  PRICE_VOLUME_PATTERN_VOLUME_RISE_PENDING: '放量上涨待承接确认',
  VOLUME_DOWN_FLOW_ACCELERATION: '放量下跌且订单流负值加速',
  FLOW_TURN_OUT_DISTRIBUTION_WARNING: '上涨中订单流转负警告',
  FLOW_TURN_IN_REBOUND_WATCH: '下跌中订单流转正观察',
  VOLUME_FLOW_STRENGTH_CONFIRMED: '放量上涨与订单流同步增强',
  VOLUME_REBOUND_CONFIRMED: '放量反弹确认',
  LOW_PANIC_SELL_GUARD: '低位禁止恐慌卖出',
  SECTOR_INCREMENT_CONFIRMED: '盘中板块增量确认',
  SECTOR_INCREMENT_WATCH: '盘中板块增量待确认',
  NEWS_NEGATIVE_IMPACT_CONFIRMED: '消息负面影响确认',
  HOLDING_NEWS_NEGATIVE_IMPACT_CONFIRMED: '持仓消息负面影响确认',
  NEWS_POSITIVE_IMPACT_CONFIRMED: '消息正面影响确认',
  HOLDING_NEWS_POSITIVE_IMPACT_CONFIRMED: '持仓消息正面影响确认',
  NEWS_PENDING_VALIDATION: '消息影响待验证',
  HOLDING_NEWS_PENDING_VALIDATION: '持仓消息影响待验证',
  NEWS_IMPACT_INVALIDATED: '消息影响已被市场证伪',
  HOLDING_NEWS_IMPACT_INVALIDATED: '持仓消息影响已被市场证伪',
  LOSS_OBSERVATION: '浮亏观察',
  critical: '严重', warning: '警告', info: '提示', RED: '红色', WATCH: '观察',
  POSITIVE_T: '正向做T', REVERSE_T: '倒T',
  OPENING_CONFIRMATION: '开盘确认', INTRADAY_HIGH_CONFIRMED: '日内高点确认',
  CLOSE_CONFIRMATION: '收盘确认', INTRADAY_EVIDENCE_SNAPSHOT: '盘中证据快照',
  WAITING_VALIDATION: '等待次日验证',
  UPSIDE_BREAKOUT: '向上突破', PULLBACK_SUPPORT_HELD: '回踩支撑有效',
  INTRADAY_LOW_CONFIRMED: '日内低点确认', SUPPORT_CONFIRMED: '支撑确认',
}

export function chineseLabel(value?: string | null) {
  if (!value) return '暂无'
  return LABELS[value] ?? value
}

export function chineseEvidence(value: string) {
  let text = value
  const replacements: Array<[RegExp, string]> = [
    [/expectation evidence missing/gi, '缺少预期证据'],
    [/real minute VWAP is unavailable/gi, '真实分钟均价线不可用'],
    [/real minute VWAP is reliable/gi, '真实分钟均价线可靠'],
    [/expectation\s+MATCHED/gi, '预期符合'],
    [/expectation\s+STRONGER/gi, '预期增强'],
    [/expectation\s+WEAKER/gi, '预期转弱'],
    [/execution state\s+/gi, '执行状态：'],
  ]
  replacements.forEach(([pattern, replacement]) => { text = text.replace(pattern, replacement) })
  Object.entries(LABELS)
    .sort(([left], [right]) => right.length - left.length)
    .forEach(([key, label]) => { text = text.replaceAll(key, label) })
  return text
}
